### ISSUE TITLE
Cadastrar Oferta

### ISSUE THREAD

**Issue by s-holmes** [npi-ufc-qxd/alocacao-professores#1]
Eu como Coordenador(a) de Curso gostaria de cadastrar uma nova oferta.

- A oferta deve conter turno, vagas, observações, turma, disciplina, professores.

- Todos os campos são de preenchimento obrigatório, exceto o de observações e o de professores.

- O campo vagas deve possuir uma ou mais vagas.

- O campo turno deve ser preenchido com um das seguintes opções: MANHA, TARDE, NOITE, MESMO_DIA

- A oferta deve estar relacionada com o período que está aberto.

- Ao digitar o nome da disciplina devem ser exibidas todas as disciplinas que correspondem ao nome digitado mostrando o nome da disciplina, possibilitando que o usuário possa selecionar a disciplina desejada. Apenas uma disciplina pode ser selecionada.

- Ao digitar o nome do professor devem ser exibidos todos os professores que correspondem ao nome digitado mostrando o nome do professor, possibilitando que o usuário possa selecionar um ou mais professores.
Uma oferta só pode ser cadastrada quando o período estiver aberto.

**Comment by CaioMelo8** [comment]
Para realização dos testes, é necessário que estejam cadastrados no banco:

- Ao menos um professor.
- Ao menos uma disciplina.
- Ao menos uma turma.

**Comment by CaioMelo8** [comment]
- Ainda precisa ser integrada com a entidade Período.

**Comment by mar-celohenrique** [comment]
Não está sendo possível efetuar o cadastro de uma oferta, pois não está sendo listado os professores.
