### ISSUE TITLE
Visualizar Detalhes do Compartilhamento

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#10]
Eu como Coordenador(a) de Curso ou Direção gostaria de visualizar os detalhes de um compartilhamento.

- Deverão ser exibidas as seguintes informações: vagas, turma, oferta.

- Mostrar opções para editar e excluir caso o período de oferta não esteja CONSOLIDADO.

**Comment by mar-celohenrique** [comment]
Não está sendo possível detalhar um compartilhamento.  A página também contém o panel duplicado onde seria exibido os datalhes.
