### ISSUE TITLE
Excluir Compartilhamento

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#11]
Eu como Coordenador(a) de Curso ou Direção gostaria de poder excluir uma oferta.

- Deve ser solicitado pedido de confirmação para exclusão de ofertas.

- A exclusão de uma oferta não poderá ocorrer caso o período da oferta esteja CONSOLIDADO.

**Comment by mar-celohenrique** [comment]
Está sendo permitida a exclusão de um compartilhamento onde o período da oferta não está consolidado.
