### ISSUE TITLE
Iniciar Período de Ofertas

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#12]
Eu como Direção gostaria de cadastrar um novo período.

- O período deve conter ano, semestre (são obrigatórios).

- O Status é definido por padrão como "ABERTO"

**Comment by s-holmes** [comment]
**Remoção Critério**
- O período é definido automaticamente baseado no período letivo atual e no seguinte, por exemplo, se uma oferta está sendo cadastrada do período de 2017.1, logo o período desta oferta será definido para 2017.2. O período deve ser exibido no formulário de cadastro.

**Comment by souzafelipe** [comment]
17/05/2017
Teste funcional na atividade 12_Iniciar_Periodo_Ofertas concluído. Por favor, verifique a planilha de reporte de bugs no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/10BxG7fUqhB9-dpULlZ05FX28ALG-2JSFAfVNPLNRPOU/edit?usp=sharing

**Comment by mar-celohenrique** [comment]
Usuário com a permissão de Coordenação é permitido inserir um novo período, o que não deve ser permitido. Deve-se restringir apenas a usuários com permissão de Direção.
