### ISSUE TITLE
Editar Período

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#13]
- Eu como Direção gostaria de alterar as informações de um período.
O usuário poderá alterar o status do período.

**Comment by souzafelipe** [comment]
Teste funcional realizado na atividade 13_editar_periodo. Por favor, verifique a planilha no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/10BxG7fUqhB9-dpULlZ05FX28ALG-2JSFAfVNPLNRPOU/edit?usp=sharing

**Comment by mar-celohenrique** [comment]
Está sendo permitido a submissão da edição com os seguintes campos vazios: Início período ajuste, Fim período direção, Fim período coordenação, Início período coordenação e 
Início período direção. Como os campos estão indo vazios, a aplicação não exibe nenhum resultado. O ideal é fazer a mesma verificação que está sendo feita quando se deixa o campo "Fim período ajuste" vazio.
