### ISSUE TITLE
Melhorias pagina Cadastrar Oferta

### ISSUE THREAD

**Issue by s-holmes** [npi-ufc-qxd/alocacao-professores#132]
- [x] No titulo da pagina deve ser informado o período ativo, por exemplo, "Ofertas 2017.1"
- [x] Adicionar o label dentro do formulário informando o curso para o qual a oferta será cadastrada, no caso, o curso do coordenador.

**Comment by amarildobarros** [comment]
Esta tarefa já não está fechada?
