### ISSUE TITLE
Cadastrar Empilhamento

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#14]
Eu como Coordenador(a) de Curso gostaria de cadastrar um novo empilhamento.

- A oferta deve conter primeira turma, primeira disciplina, segunda turma, segunda disciplina.

- Todos os campos são de preenchimento obrigatório.

- Ao digitar o nome das turmas devem ser exibidas todas as disciplinas que correspondem ao nome digitado mostrando o nome da turma, possibilitando que o usuário possa selecionar a turma desejada. Apenas uma turma pode ser selecionada.

- Ao digitar o nome das disciplinas devem ser exibidas todas as disciplinas que correspondem ao nome digitado mostrando o nome da disciplina, possibilitando que o usuário possa selecionar a disciplina desejada. Apenas uma disciplina pode ser selecionada.

- Um empilhamento só pode ser cadastrado quando o período estiver aberto.

**Comment by Phellipehz** [comment]
Agora vai @souzafelipe

**Comment by souzafelipe** [comment]
Teste funcional executado na atividade 14_cadastrar_empilhamento. Por favor, verifique a planilha de reporte de bugs no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/1C_3QgRpZq9OnO25eRE5qIF6MyAp0kmIEmswt9dLtF9U/edit?usp=sharing

**Comment by mar-celohenrique** [comment]
Está sendo possível empilhar duas disciplinas iguais dos mesmos semestres e mesmas turmas, o que não pode acontecer.

Está sendo permitido o empilhamento mesmo com nenhum período aberto, o que não pode acontecer.

Está sendo permitido duplicar um empilhamento, isto é, depois de já empilhadas tumas e disciplinas, é possível realizar um novo empilhamento com essas mesmas turmas e disciplinas.
