### ISSUE TITLE
Visualizar Lista de Empilhamentos

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#15]
Eu como Coordenador(a) de Curso ou Direção gostaria de visualizar a lista de todos os empilhamentos.

- Deverá ser exibida a lista de todos os empilhamentos.Dever ser exibida todas as informações do empilhamento: primeira turma e disciplina, segunda turma e disciplina

**Comment by souzafelipe** [comment]
22/05/2017
Teste funcional realizado na atividade 16_visualizar_lista_empilhamento. Por favor, acesse a planilha de reporte de bugs no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/1C_3QgRpZq9OnO25eRE5qIF6MyAp0kmIEmswt9dLtF9U/edit?usp=sharing
