### ISSUE TITLE
Excluir Empilhamento

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#17]
Eu como Coordenador(a) de Curso gostaria de poder excluir um empilhamento.

- Deve ser solicitado pedido de confirmação para exclusão de empilhamentos.

**Comment by souzafelipe** [comment]
Teste funcional realizado na atividade 18_excluir_empilhamento. Por favor, verifique a planilha de reporte de bugs no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/1C_3QgRpZq9OnO25eRE5qIF6MyAp0kmIEmswt9dLtF9U/edit?usp=sharing

**Comment by mar-celohenrique** [comment]
Ao excluir um empilhamento, está sendo aberta uma nova página contendo o resultado JSON da requisição ajax. O ideal é redirecionar para a mesma página de listagem dos empilhamentos.
