### ISSUE TITLE
Refatorar Listagem Empilhamento

### ISSUE THREAD

**Issue by s-holmes** [npi-ufc-qxd/alocacao-professores#175]
Deletar a entidade Empilhamento.

Criar a classe RestricaoHorario com os seguintes atributos(id, primeiraOferta, segundaOferta, habilitada, tipo[EMPILHAMENTO, DISTINTO], periodo)

Na listagem de Empilhamentos deve ser apresentadas as Restrições de horario cujo o tipo seja EMPILHAMENTO. A tabela deve conter o seguinte cabeçalho: Primeira Oferta, Segunda Oferta,  Habilitada, Coluna de opções com titulo em branco.

**Comment by souzafelipe** [comment]
Formato:  SI - 1 - MATEMÁTICA BÁSICA
