### ISSUE TITLE
Cadastrar Disciplina

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#18]
Eu como Coordenador(a) de Curso ou Direção gostaria de cadastrar uma nova disciplina.

- A disciplina deve conter nome, créditos, carga horária teórica e carga horária prática.

- Todos os campos são de preenchimento obrigatório.

**Comment by souzafelipe** [comment]
Teste executado na atividade. Favor verificar a planilha de reporte de bugs no Google Docs.

**Comment by souzafelipe** [comment]
23/05/17
Teste funcional realizado na atividade. Favor verificar a planilha de reporte de bugs no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/1RehTkej9rasEdwmAIL0RkUdTXc6oWWfD_CzpmShDu_E/edit?usp=sharing
