### ISSUE TITLE
Editar Disciplina

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#19]
Eu como Coordenador(a) de Curso ou Direção gostaria de alterar as informações de uma disciplina.

- O usuário poderá alterar todos os campos.

**Comment by souzafelipe** [comment]
09/05/2017
Teste funcional realizado na atividade. Favor consultar a planilha de reporte de bugs no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/1RehTkej9rasEdwmAIL0RkUdTXc6oWWfD_CzpmShDu_E/edit?usp=sharing

**Comment by souzafelipe** [comment]
29/05/2017
Teste funcional realizado na atividade. Favor consultar a planilha de reporte de bugs no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/1RehTkej9rasEdwmAIL0RkUdTXc6oWWfD_CzpmShDu_E/edit?usp=sharing

**Comment by souzafelipe** [comment]
O sistema não permite que disciplinas com hífen (-) em "Nome da Disciplina" sejam cadastradas.

**Comment by souzafelipe** [comment]
07/06/2017
- Remover a barra final da URL de "Editar". O correto é /{idDisciplina}/editar. A permanência da barra está implicando em um erro quando é acionado o "Editar" a partir da página de "Listar".
- Recomendação do Rayson: O input deve estar com a borda vermelha quando ocorrer algum erro no preenchimento dos campos.
- Recomendação do Rayson: A mensagem deve estar vermelha quando ocorrer algum erro no preenchimento dos campos.
