### ISSUE TITLE
Editar Empilhamento

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#2]
Eu como Coordenador(a) de Curso ou Direção gostaria de alterar as informações de um empilhamento.

- O usuário poderá alterar todos os campos.

- Um empilhamento só pode ser editada quando o período estiver aberto.

- A Direção poderá alterar um empilhamento quando o período estiver ABERTO ou EM ANÁLISE.

**Comment by souzafelipe** [comment]
30/05/2017
Teste funcional realizado na atividade. Por favor, verifique a planilha de reporte de bugs no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/1C_3QgRpZq9OnO25eRE5qIF6MyAp0kmIEmswt9dLtF9U/edit?usp=sharing
