### ISSUE TITLE
Visualizar Lista de Disciplinas

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#20]
Eu como Coordenador(a) de Curso ou Direção gostaria de visualizar a lista de todas as disciplinas.

- Deverá ser exibida a lista de todas as disciplinas.

- Mostrar opções para editar e arquivar.

**Comment by s-holmes** [comment]
Aplicar Arquivo de Tradução do DataTables
https://datatables.net/plug-ins/i18n/Portuguese-Brasil

**Comment by souzafelipe** [comment]
15/05/2017
Teste funcional realizado na atividade 21_VISUALIZAR_LISTA_DE_DISCIPLINAS. Por favor consulte a planilha de reporte de bugs no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/1RehTkej9rasEdwmAIL0RkUdTXc6oWWfD_CzpmShDu_E/edit?usp=sharing
