### ISSUE TITLE
Arquivar Disciplina

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#22]
Eu como Coordenador(a) de Curso gostaria de poder arquivar uma disciplina.

- Deve ser solicitado pedido de confirmação para o arquivamento da disciplina.

- Adicionar o campo booleano "arquivada" na entidade Disiciplina

- Uma disciplina arquivada não deve ser apresentada na lista de Disciplinas (Essa restrição deve ser feita na consulta)

**Comment by s-holmes** [comment]
http://docs.spring.io/spring-data/jpa/docs/2.0.0.M3/reference/html/#jpa.query-methods

**Comment by souzafelipe** [comment]
23/05/2017
Teste funcional realizado na atividade 24_Arquivar_Disciplina.
Observação: Seria bom se a página fosse atualizada automaticamente após o arquivamento de uma disciplina. A não atualização e a consequente não remoção da disciplina arquivada da página pode deixar o usuário confuso.
