### ISSUE TITLE
Editar Oferta

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#4]
Eu como Coordenador(a) de Curso ou Direção gostaria de alterar as informações de uma oferta.

- O usuário poderá alterar todos os campos exceto período.

- Uma oferta só pode ser editada quando o período estiver aberto.

**Comment by CaioMelo8** [comment]
Para realização dos testes, é necessário que estejam cadastrados no banco:

- Ao menos um professor.
- Ao menos uma disciplina.
- Ao menos uma turma.
- Ao menos uma oferta.

**Comment by CaioMelo8** [comment]
- Ainda precisa ser integrada com a entidade Período.

**Comment by mar-celohenrique** [comment]
Não está sendo exibida a página de edição da oferta.
