### ISSUE TITLE
Excluir Oferta

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#6]
Eu como Coordenador(a) de Curso ou Direção gostaria de poder excluir uma oferta.

- Deve ser solicitado pedido de confirmação para exclusão de ofertas.

- A exclusão de uma oferta não poderá ocorrer caso o período da oferta esteja CONSOLIDADO.

**Comment by CaioMelo8** [comment]
Para realização dos testes, é necessário que estejam cadastrados no banco:

- Ao menos um período.
- Ao menos uma oferta cujo período esteja com status "ABERTO".

**Comment by CaioMelo8** [comment]
- Ainda precisa ser integrada com a entidade Período.

**Comment by mar-celohenrique** [comment]
A oferta está sendo excluída conforme o esperado.
