### ISSUE TITLE
Ajustar Front-End Periodo ao novo Layout

### ISSUE THREAD

**Issue by s-holmes** [npi-ufc-qxd/alocacao-professores#67]

**Comment by souzafelipe** [comment]
07/06/2016
   Listar Período
        - Inserir o botão "Editar" para que um período possa ser editado.
        - Excluir da "white-box" o título "Lista de Períodos"
        - Recomendação: Inclusão de um botão "Excluir", para excluir um período cadastrado.

   Cadastrar Período
        - Problema: Não é possível cancelar o cadastro de um período sem que seja necessário 
          preencher os campos "Ano" e "Semestre".
        - Problema: Ao se preencher os campos "Ano" e "Semestre" e clicar em "Cancelar" um     
          novo período é cadastrado no sistema.
        - Problema: O sistema permite o cadastro de um novo período com a data do "Fim Período 
          Coordenação" anterior ao "Início Periodo Coordenação"
        - Problema: O sistema permite o cadastro de um novo período com a data do "Fim Período 
          Direção" anterior ao "Início Periodo Direção"
        - Problema: O sistema permite o cadastro de um novo período com a data do "Fim Período 
          Ajuste" anterior ao "Início Periodo Ajuste"

   Editar Período
        - Problema: Ao editar um período e clicar em "Editar" o usuário é direcionado para uma 
          página em branco.
        - Problema: Ao tentar cancelar a edição de um período o usuário é direcionado para uma 
          página em branco.

**Comment by souzafelipe** [comment]
14/06/2017

Listar Período

- Mudar a cor do botão "Excluir" para vermelho (ou o mais próximo disso).
- Mudar o ícone dentro do botão excluir. Ao invés da caneta poderia ser uma lixeira ou um "X".
- Ajustar a fonte do título "Períodos", de maneira que se adeque a fonte utilizada nos títulos das 
  outras páginas do mesmo épico.

Cadastrar Período

- Problema: Não é possível cancelar o cadastro de um período sem que seja necessário 
  preencher todos os campos.
- Problema: Ao preencher todos os campos e clicar em "Cancelar", um novo período é 
  cadastrado no sistema.
- Verificar com o Rayson a regra de negócio sobre início e fim dos períodos para a direção e a  
  coordenação. No momento não está sendo possível cadastrar as datas de início e fim para a 
  direção antes da coordenação, não temos informações se funciona realmente desta forma.

Editar Período

- Problema: Durante a edição de um périodo ao clicar em "Cancelar", o período em questão é 
  modificado.


OBS 1: Após o cadastro de um novo período as informações como início período coordenação, fim do período coordenação..., não poderão ser editadas? Caso eu cometa um erro no cadastro terei que excluir aquele período e refazer tudo novamente?

OBS 2: Já que existem informações que vão além de "Ano", "Semestre" e "Status". Deveria haver um local onde essas outras informações pudessem ser visualizadas.

**Comment by souzafelipe** [comment]
20/07/2017

Listar Período

- Remover as informações "Início Período Coordenação", "Fim Período Coordenação","Início 
  Período Direção", "Fim Período Direção". Verificar com o Rayson a possibilidade de colocar 
  essas informações em outra página.
	
Cadastrar Período

- Verificar com o Rayson a regra de negócio sobre início e fim dos períodos para a direção e a 
   coordenação. No momento não está sendo possível cadastrar as datas de início e fim para a 
   direção antes da coordenação ou até mesmo para o mesmo período, não temos informações 
   se funciona realmente desta forma. 

Editar Período

- Mudar as palavras "Aberta" e "Consolidada" do feminino para o masculino.

Excluir Período

- Problema: Ao excluir um período que esteja atrelado a uma oferta o usúario é direcionado 
  para uma página em branco. Uma possível solução seria colocar um alerta avisando que não é  
  possível excluir aquele período.
- Inserir um alerta antes da excluir definitivamente um período. Ao clicar em "Excluir" uma 
  mensagem deve ser mostrada perguntando se o usuário tem certeza da exclusão.

**Comment by souzafelipe** [comment]
- Recomendação: Mudar a frase exibida no alerta gerado ao excluir um período relacionado a uma oferta, para "O período não pode ser excluído, pois existe uma oferta de disciplina relacionada a ele."
- Recomendação: Remover da página de listar o título da coluna "Opções".
