### ISSUE TITLE
Ajustar Front-End Empilhamentos ao novo Layout

### ISSUE THREAD

**Issue by s-holmes** [npi-ufc-qxd/alocacao-professores#69]

**Comment by souzafelipe** [comment]
- Inserir no título da página o título "Cadastrar Empilhamento".
- Adicionar funcionalidade ao botão "Cancelar".
- Remover o botão "Novo Empilhamento".
- Remover classe m-r-20 do botão editar
- Inverter posições do botão "Cadastrar" e "Cancelar"
