### ISSUE TITLE
US01 – Solicitar Compartilhamento

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#7]
Eu como Coordenador(a) de Curso gostaria de solicitar um novo compartilhamento.

- O compartilhamento deve conter vagas, turma, oferta.

- Todos os campos são de preenchimento obrigatório.

- O campo vagas deve possuir uma ou mais vagas.

- Um compartilhamento só pode ser solicitado quando o período estiver aberto.

**Comment by souzafelipe** [comment]
29/05/2017
Teste funcional executado na atividade. Favor verificar a planilha no Google Docs. Link da planilha:  https://docs.google.com/spreadsheets/d/13bN0R_9xh3GTYAcy_BJVRw1QqHS4AS2NZ5VPGtJ2VTg/edit?usp=sharing

**Comment by mar-celohenrique** [comment]
Não está sendo exibida toda a lista das ofertas do período que está aberto.
