### ISSUE TITLE
Listar Compartilhamentos

### ISSUE THREAD

**Issue by s-holmes** [npi-ufc-qxd/alocacao-professores#77]
Eu como Coordenador(a) de Curso ou Direção gostaria de visualizar a lista de todos os compartilhamentos.

 - Deverá ser exibida a lista de todos os compartilhamentos correspondentes ao período que estiver aberto.
 - Mostrar opções para editar, excluir, detalhes, solicitar compartilhamento caso o período de oferta não esteja CONSOLIDADO.

**Comment by mar-celohenrique** [comment]
Não está sendo possível exibir a página de listagem de compartilhamentos quando não há nenhum compatilhamento cadastrado.
