### ISSUE TITLE
Corrigir Editar Empilhamento

### ISSUE THREAD

**Issue by s-holmes** [npi-ufc-qxd/alocacao-professores#78]
Corrigir erros Editar Empilhamento
	Problema: Não ocorre a listagem de disciplinas e turmas para que a edição possa ser realizada.
	Remover titulo "EDITAR EMPILHAMENTO" da "white-box" e manter no titulo da Pagina o seguinte titulo: "Editar Empilhamento"
	Remover o botão "Novo Empilhamento" da pagina Editar Empilhamento
	Corrigr label botão editar, deve ser "editar" e não "cadastrar"
	Remover classe m-r-20 do botão editar
	Inverter posições do botão editar e cancelar

**Comment by s-holmes** [comment]
https://github.com/npi-ufc-qxd/alocacao-professores/issues/2

Issue 15 no zube

**Comment by mar-celohenrique** [comment]
O botão de cadastro de empilhamento na página de edição continua presente. Ele deve ser removido.
