### ISSUE TITLE
Editar Compartilhamento

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#8]
Eu como Coordenador(a) de Curso ou Direção gostaria de alterar as informações de um compartilhamento.

- O usuário poderá alterar todos os campos.

- Um compartilhamento só pode ser editado quando o período estiver aberto.

**Comment by mar-celohenrique** [comment]
O botão de submissão da edição do compartilhamento está com o nome de "Cadastrar", o ideal seria "Editar".
