### ISSUE TITLE
Lista de Compartilhamentos

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/alocacao-professores#9]
Eu como Coordenador(a) de Curso ou Direção gostaria de visualizar a lista de todos os compartilhamentos.

- Deverá ser exibida a lista de todos os compartilhamentos correspondentes ao período que estiver aberto. 

- Mostrar opções para editar e excluir caso o período de oferta não esteja CONSOLIDADO.

**Comment by souzafelipe** [comment]
23/05/2017
Teste funcional realizado na atividade 9_visualizar_lista_compartilhamento. Por favor, acesse a planilha de reporte de bugs no Google Docs. Link da planilha: https://docs.google.com/spreadsheets/d/13bN0R_9xh3GTYAcy_BJVRw1QqHS4AS2NZ5VPGtJ2VTg/edit?usp=sharing
